<?php include "top.php"?>
<div class = "heading italic">When I lost my mobile for the umptieth time...</div>
<div class = "subheading italic">15-08-2016</div>
<div class = "text italic">The number of times that I have misplaced or lost my cellphone is so high that I might as well add it to my hobby list. It was a melancholy day, my last day at IIT Bombay, having attended my convocation the previous Saturday. I was staying with my parents in Kalyan. My aunt, the only connection to my clan in Mumbai, owns a 1 BHK apartment there. She was a beloved companion during my four year stay in college. Whether I felt sick of mess food or felt homesick, she was always there to comfort me.
<div class = "vertical-space"></div>
So, I was headed back towards Kalyan after brushing up a consultancy project at IITB. I had two delicious burgers and a glass of sugarcane juice on my way. Only after I ascended the stairs to platform 1 of Kanjurmarg that my sixth sense triggered me to check for my belongings. It was soon obvious, I had done it again. My cellphone was no where to be found. I checked my backpack and dress pockets numerous times to confirm my situation. An unconscious flashback to my time outside department building reminded that I was in possession of my mobile when I left the lab. Therefore, it was useless to retrace my path back to college. Whether I liked it or not, I had repeated the recklessness of my colleagues who would drop their stuffs in public places. 
<div class = "vertical-space"></div>
An middle class employee was passing by when I urged him to lend his mobile phone. He glared at me as if I were a terrorist and passed by without any further response. Perchance my improper taste of dressing accounted for his refusal. Another attempt of request with a teenage boy got me hold of a mobile phone. I hurriedly punched my mobile number and called. Luckily, it connected on the first attempt but unfortunately no one received the call. I went back to the place where I had burgers and re-tried my number. This time the autorickshaw driver received the call and after 5 minutes of banter, we decided to meet at a place easy to identify.
<div class = "vertical-space"></div>
I called for the service of several autorickshaws before a middle aged driver took pity of me and offered a ride. He knew I was in distress and after I recapitulated my situation at a traffic jam, he offered me his mobile phone out of no where. I was flabbergasted. At the end of the day, it was this unforeseen gesture by an auto driver that forced me to write this piece. He taught me a lesson of my life which is too complex to be formulated in words. I only wonder whether or not I would have offered my mobile to a stranger if I was in the shoes of that middle class employee.
<div class = "vertical-space"></div>
I am heading for the next stage of my life. One day I might be richer than most of the people I encountered that day. But I would consider myself successful only if I could inculcate the helping attitude of that auto driver.
</div>
<?php include "bottom.php"?>
